### ISSUE TITLE
Entity Resolution Implementation

### ISSUE THREAD

**Issue by falahat** [datactive/bigbang#151]
Since we want to implement entity resolution, we should think about how to actually use it in the code. I've written an algorithm already that runs in linear time and does a decent(ish) job of resolving identities, but it's not graceful/intuitive to actually apply to a dataframe. 

For example, should it be an interface where someone can pass in a dataframe of (Name, Email) entries and have the algorithm spit out a (Name, Email, Unique_ID) ?

There are more general questions like:
- Input format
- Output format
- Setup methods
- Mutating input vs. returning a new table
- Resolving across multiple dataframes
- Reporting accuracy

This isn't a pressing matter, so we can definitely wait on it, but I just wanted to throw this up here for future reference.

**Comment by sbenthall** [comment]
This is an excellent question. It ties in with some other problems I've been dealing with in email parsing, detecting quoted text (#150) and signatures (#147). The problem is that since detecting what is quoted can depend on information about which emails come prior in a thread, and detecting email signatures can depend on detecting quoted text *and vice versa*, the proprocessing logic is going to have to be quite gnarly.

We could do these operations as multiple passes on a Pandas DataFrame. Another possibility--which would be perhaps better in terms of open source citizenship, would be to write a lower level Python framework for preprocessing .MBOX files without the scipy dependencies, which could be a lot of overhead for people. I could see this sort of thing potentially getting a lot of independent use.
