### ISSUE TITLE
Archive directory created outside repository

### ISSUE THREAD

**Issue by davidberra** [datactive/bigbang#301]
I guess this is not intended and it is the reason why i can't load data from notebooks?

**Comment by davidberra** [comment]
ok looking into collect_mail.py i see that the destination directory is now an argument of the script.
this is something new? keeping this issue open because i guess this impact how notebooks load data and i cant quite figure out the best way to deal with it

**Comment by sbenthall** [comment]
Thanks for making this issue. It's true the current behavior is strange.

This is related to issue #117 though I think the behavior has changed since that older ticket.

My sense is that the cause for confusion is that the mail collecting functionality takes an archives directory argument which is by default specified as a relative path. But this functionality is called from many different places in the file hierarchy, resulting in oddly placed and duplicate archive directories.

I believe that enhancement #113 is the right way to solve these problems: having a config option that specifies the archive path in a stable way, and using this as the default.

**Comment by npdoty** [comment]
I think this should be resolved now. If you specify a parameter to collect_mail, you can collect archives into a specific folder (which you might want to do when you're working on a particular corpus, etc.). When no parameter is specified, the default is now still "archives" but it won't be in a different place based on where you called the script from, it'll be relative to the config file, and by default it'll be in the main `bigbang` directory.
