### ISSUE TITLE
folder convention

### ISSUE THREAD

**Issue by davidberra** [datactive/bigbang#307]
are we gonna call the directory under 'archives' with the full url or with the name of the mailing list?

e.g.
http://www.ietf.org/mail-archive/text/ietf-privacy or ietf-privacy?

I remember we agreed on the first, but collect_mail still follow the second convention (while notebooks are totally inconsistent on that)

**Comment by sbenthall** [comment]
I believe this is because we tried to provide a convenience to the user.

If you supply a full URL in the notebook and the data has not yet been downloaded, BigBang will download it for you (it calls this load_data method). If the data has been downloaded, it will use the data you have locally:

https://github.com/datactive/bigbang/blob/master/bigbang/mailman.py#L49

If you give it the shorter name of the list (i.e. "ietf-privacy") then it can still find the files if they are in the right archive subdirectory.

I am +0 on using full URLs in the notebook as a convention.

**Comment by nllz** [comment]
The new notebooks have the names of the lists and relative paths to 'archives'.
