### ISSUE TITLE
ImportError: No module named config.config

### ISSUE THREAD

**Issue by Nasiff** [datactive/bigbang#356]
I am Nasif and I am a student assistant for Professor Stephen Couture at York University.
I was trying to install BigBang in my Anaconda environment on Windows 10 and even after following all the steps. I just couldn't get past this ImportError that keeps on saying that it can't find the config.config module.

Using Python 2.7.1 in an Anaconda environment (Version: Anaconda 2018.2) on a Windows 10 machine (Version: 10.0.17134 Build 17134).

I also repeated the same steps in my Windows 10 environment running Python 2.7 and I still get stuck at the same error.

Anaconda environment with the bigbang script activated: 

![image](https://user-images.githubusercontent.com/29618544/51287873-a04b8180-19c7-11e9-8bf4-c01c7b05f667.png)

Same error on my Win10 environment (Using the Git Bash terminal to execute unix code)  and this time I activated the bigbang script (Using 'source activate bigbang'):

![windows 10 environment](https://user-images.githubusercontent.com/29618544/51286340-95d9b980-19c0-11e9-87e7-427fd96c8c31.png)

Edit: Typos and formatting

**Comment by npdoty** [comment]
Thanks for noting the issue and sorry for the frustration here. This looks like an install issue, but I don't have a Windows 10 box to reproduce it exactly. If you ran the `conda-setup.sh` script, then you used pip to install bigbang in "editable" (-e) mode, so that it would be available to python but also you could continue to make changes to the files. For whatever reason, your installation isn't seeing the `config` submodule inside of the bigbang directory, although bigbang is installed as an egg under `bdist.win32`.

It might be that we need to switch to absolute imports per [PEP 328](https://docs.python.org/2.5/whatsnew/pep-328.html), or it might be that there's some issue with Windows installation where `pip install -e` isn't appropriate. @sbenthall, is this something you're familiar with? Do we need to explicitly list the config sibling/submodule in `setup.py`?

@Nasiff, if you're comfortable with Python development on Windows more generally, you could also uninstall bigbang with pip and just try to run it as available from the current directory; I'm not sure why Python didn't use the current directory as a backup to look for `config.config` already, to be honest.

**Comment by Nasiff** [comment]
Thanks for looking into it @npdoty . So I uninstalled BigBang using pip and then I tried to reinstall without using the "bigbang" environment in Anaconda (I just installed using the (base) environment). I now have a new error which is an extension of my original error. I now get an IOError: [Errno 2] No Such File or Directory.
The screen grab here makes it clearer:
![ioerror](https://user-images.githubusercontent.com/29618544/51647399-a05cfb80-1f4a-11e9-89d5-c3ee83447e49.png)
After seeing the different kinds of slashes in the _IOError_: I am beginning to think this is a windows specific issue as it probably couldn't recognize the _config.yml_ file that was right inside config folder.

**Comment by npdoty** [comment]
@Nasiff I think the double slashes aren't a problem (it's the `repr` version of the string for error message printing), but the "confi/" portion is because of an apparent bug in `config.py` that assumes and searches for a forward slash, which won't be Windows compatible. I'll create a branch with a fix for you to try out.

**Comment by npdoty** [comment]
@Nasiff could you try pulling from this branch and see if you're unblocked?
https://github.com/datactive/bigbang/tree/config-path-fix
There may be other paths (including in `config.yml`, actually) which are assuming Unix-style path separators, and we haven't had much testing on Windows, so please let us know what you run into.

**Comment by Nasiff** [comment]
Well, that fixed everything. It's actually downloading all the scipy-dev emails right now. Thanks!
