### ISSUE TITLE
ModuleNotFoundError: No module named 'graph' // multiple notebook issue

### ISSUE THREAD

**Issue by nllz** [datactive/bigbang#426]
Several notebooks, such as notebooks/InteractionNetwork.ipynb, rely on:

import bigbang.graph as graph

but 

----> 6 import graph

fails with:

ModuleNotFoundError: No module named 'graph'

**Comment by sbenthall** [comment]
Ok. I've figured this out.

Recall the earlier problem with `sudo`. That had to do with one command that for some reason is not in the conda installation, but remains in the pip installation.

`python setup.py develop` installs the package into the environment locally with hooks so that when you edit the source code in the development directory, it changes the Python environment.

A complication with this is that by default, it installs this into a root package. To avoid this, you can install in a user's directory.

`python setup.py develop --user`

See discussion [here](https://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install).

Note that there is a `conda develop` command that is supposed to do the same thing, but the consensus [is it is not well documented or maintained](https://github.com/conda/conda-build/issues/1992). 

`pip install -e .` is supposed to do the same thing as `python setup.py develop`. We do include this line in the requirements, but for some reason it is not working.

https://github.com/datactive/bigbang/blob/master/requirements.txt#L1

Reasons might be:
 - it should be after the other requirements
 - it should not be in the requirements file but should stand alone as an additional command

Note also that when I tried this, I got an error with the Levenshtein package installation, which is resolved by installing the development version of Python. See [here](https://stackoverflow.com/questions/26053982/setup-script-exited-with-error-command-x86-64-linux-gnu-gcc-failed-with-exit).

A tricky thing about this is that we have been providing installation instructions assuming that somebody is installing it to develop the software. That is a different use case from somebody who wants to install it to use it for analysis. Ideally, there would be two instruction sets. Of course, at this stage we don't have many pure "users" ...
