### ISSUE TITLE
generalize w3crawl to other list archives?

### ISSUE THREAD

**Issue by sbenthall** [datactive/bigbang#73]
Thanks, @npdoty, for the contributions in #54 

I see that there is no a w3c specific subroutine to the mailman.py file. I'm wondering about the best way to organize this moving forward, especially as we looking into multiple sources of data (like git repositories).

Ideally, we would be able to connect to many different mailing lists hosts, generically, rather than have routines for specific sources.

Is it possible to find out what software is hosting w3c mailing lists, and make this code work generically against them?

**Comment by npdoty** [comment]
Related to #284, it would be nice if BigBang could find the archive URL, determine what kind of archive it is and use the appropriate method to collect the archives. Currently we're doing a basic version of this with regular expression matching on the URL, which we may want to one day improve since the URL won't always be enough information. For now, I don't think the W3C crawl infrastructure needs to be generalized, although if someone wants to explore more generic Hypermail archive collection (for Unicode or any other users we find of some version of that software), I'm open to it.

I believe we should close this issue for now.

**Comment by sbenthall** [comment]
Good point. Closing.
